#!/usr/bin/env bash
# This script was written by textandmetal@gmail.com

# Read from dictionary file and download as keyword search from maoridictionary.co.nz
while read i; do 
	clear
	wget "https://maoridictionary.co.nz/search?idiom=&phrase=&proverb=&loan=&histLoanWords=&keywords=$i"
done < dictionary.txt
